#ifndef TIMERS_CONFIG_H
#define TIMERS_CONFIG_H

#define TIMER_TIMER0_PRELOADVAL_NORMAL_MODE	  	 192
#define TIMER_TIMER0_OVFVAL_NORMAL_MODE		  	 3907	

#define TIMER_TIMER0_Compare_Match_Val			 99
#define TIMER_TIMER0_DESIRED_TIME_CTC_MODE_ISR	 10000	

#define TIMER0_MODE								 TIMER0_NORMAL_MODE
#define TIMER0_PRESCALER						 TIMER_DIV8

#endif